title: tehmasp chaudhri # name of the site
author: Tehmasp Chaudhri # name of site's author
email: tehmasp@chaudhri.me # email of site's author
url: https://tehmasp.com # root address of the site
baseurl: "" # subpath of the site, e.g. "/blog"
description: > # description of the site (multiple lines allowed)
  personal website.

permalink: /:slug.html

favicon: "favicon.ico" # name+extension of favicon (which must be put on the root folder)
# goat_counter: "yoursitename" # put your GoatCounter name if you want to use GoatCounter analytics

remote_theme: riggraz/no-style-please

theme_config:
  appearance: "light" # can be "light", "dark" or "auto"
  back_home_text: ".." # customize text for homepage link in post layout
  date_format: "%Y-%m-%d" # customize how date is formatted
  show_description: false # show blog description in home page

sass:
  style: :compressed

plugins:
  - jekyll-feed
  - jekyll-seo-tag
